Globals:
    Function:
        Timeout: 10

Resources:
    HelloWorldFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: .
            Handler: index.lambdaHandler
            Runtime: nodejs18.x
            Architectures:
                - x86_64
            Events:
                HelloWorld:
                    Type: Api
                    Properties:
                        Path: /
                        Method: post
